name: Release

on:
  release:
    types: [published]

jobs:
  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # Only run on non-draft releases
    if: github.event.release.draft == false
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Publish to crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}