name: Release Drafter

on:
  # Manual trigger only to avoid quota usage
  workflow_dispatch:
  # Uncomment below to re-enable automatic draft release
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}