name: Release

on:
  # Manual trigger only to avoid quota usage
  workflow_dispatch:
  # Uncomment below to re-enable automatic release
  # release:
  #   types: [published]

jobs:
  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # Only run on non-draft releases
    if: github.event.release.draft == false
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Publish to crates.io (dry-run for testing)
      run: |
        if [[ "${{ github.repository }}" == *"-test" ]]; then
          echo "Test repository detected - running dry-run"
          cargo publish --dry-run
        else
          echo "Production repository - publishing to crates.io"
          cargo publish
        fi
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}